global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']