"""Change Theme, Question models

Revision ID: 77e600839422
Revises: fde27b0c190a
Create Date: 2025-04-20 21:37:55.589661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e600839422'
down_revision: Union[str, None] = 'fde27b0c190a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_game_winner_id', 'game', 'game_player', ['winner_id'], ['id'], deferrable=True, use_alter=True)
    op.alter_column('question', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('question_theme_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'theme', ['theme_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'theme', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theme', type_='unique')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_theme_id_fkey', 'question', 'theme', ['theme_id'], ['id'])
    op.alter_column('question', 'theme_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_game_winner_id', 'game', type_='foreignkey')
    # ### end Alembic commands ###
