"""Change User

Revision ID: e3f19c98f371
Revises: 591121b7eccd
Create Date: 2025-04-15 19:34:58.112506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3f19c98f371'
down_revision: Union[str, None] = '591121b7eccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_game_winner_id', 'Game', 'GamePlayer', ['winner_id'], ['id'], deferrable=True, use_alter=True)
    op.alter_column('User', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('fk_game_winner_id', 'Game', type_='foreignkey')
    # ### end Alembic commands ###
