"""Add settings into Game

Revision ID: 2a593aa7de48
Revises: 0cad6b1092fe
Create Date: 2025-04-24 00:50:38.150659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a593aa7de48'
down_revision: Union[str, None] = '0cad6b1092fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('manager_id', sa.BigInteger(), nullable=True))
    op.add_column('game', sa.Column('time_for_answer', sa.Integer(), server_default='20', nullable=False))
    op.add_column('game', sa.Column('time_for_game', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('reg_start_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'game', 'theme', ['theme_id'], ['id'])
    op.create_foreign_key('fk_game_manager_id', 'game', 'game_player', ['manager_id'], ['id'], deferrable=True, use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_game_manager_id', 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'theme_id')
    op.drop_column('game', 'time_for_game')
    op.drop_column('game', 'time_for_answer')
    op.drop_column('game', 'manager_id')
    op.drop_column('game', 'reg_start_time')
    # ### end Alembic commands ###
